# Configurações do Banco H2 em memória
spring.datasource.url=jdbc:h2:mem:agendamentodb;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# URL padrão do React em desenvolvimento local
app.cors.allowed-origins=http://localhost:5173

# ====================================================================
# CONFIGURAÇÃO DO GOOGLE OAUTH2
# ====================================================================
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}

# Solicitamos permissão para o perfil do usuário E para gerenciar o calendário
spring.security.oauth2.client.registration.google.scope=openid,profile,email,https://www.googleapis.com/auth/calendar

# Força o Google a sempre devolver o 'refresh_token' (fundamental para não expirar o acesso do barbeiro)
spring.security.oauth2.client.registration.google.authorization-grant-type=authorization_code