spring.application.name=agendamento

# Configurações do Banco H2 em memória
spring.datasource.url=jdbc:h2:mem:agendamentodb;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Ativa o console web do H2 para você conseguir olhar o banco pelo navegador
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Configurações do Hibernate / JPA
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# 'update' cria/atualiza as tabelas automaticamente baseado nas classes Java
spring.jpa.hibernate.ddl-auto=update

# Exibe os SQLs que o Spring gerar no terminal (ótimo para debugar)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Garante que o script 'import.sql' ou 'data.sql' seja executado APÓS o Hibernate criar as tabelas
spring.jpa.defer-datasource-initialization=true